from __future__ import annotations

import hashlib
import json
import platform
import re
import shutil
import subprocess
import textwrap
from dataclasses import dataclass
from pathlib import Path

from . import __version__
from .builder import _copy_source, _environment_file, _service, _write_text
from .errors import ImageBuildError
from .manifest import Manifest


RPI_IMAGE_GEN_VERSION = "v2.7.0"
RPI_IMAGE_GEN_COMMIT = "a7b6d4806183195f3efadb533f58c8e46393d057"
HOSTNAME_PATTERN = re.compile(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?")
SSH_KEY_PATTERN = re.compile(
    r"(?:ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp(?:256|384|521)|"
    r"sk-ssh-ed25519@openssh\.com|sk-ecdsa-sha2-nistp256@openssh\.com) "
    r"[A-Za-z0-9+/=]+(?: [^\r\n]*)?"
)


@dataclass(frozen=True)
class ImagePlan:
    workspace: Path
    config_path: Path
    layer_path: Path
    image_name: str
    target: str


@dataclass(frozen=True)
class ImageResult:
    path: Path
    sha256: str
    plan: ImagePlan


def _yaml_packages(packages: tuple[str, ...]) -> str:
    return "\n".join(f"    - {package}" for package in packages)


def _runtime_hook(manifest: Manifest) -> str:
    slug = manifest.app.slug
    app_dir = f"/opt/repobox/apps/{slug}"
    if manifest.app.runtime == "python":
        return f"""chroot --userspec=repobox:repobox "$1" python3 -m venv "{app_dir}/.venv"
if [ -f "$1{app_dir}/current/requirements.txt" ]; then
  chroot --userspec=repobox:repobox "$1" "{app_dir}/.venv/bin/python" -m pip install --disable-pip-version-check -r "{app_dir}/current/requirements.txt"
elif [ -f "$1{app_dir}/current/pyproject.toml" ]; then
  chroot --userspec=repobox:repobox "$1" "{app_dir}/.venv/bin/python" -m pip install --disable-pip-version-check "{app_dir}/current"
fi"""
    return f"""if [ -f "$1{app_dir}/current/package-lock.json" ]; then
  chroot --userspec=repobox:repobox "$1" npm --prefix "{app_dir}/current" ci --omit=dev
else
  chroot --userspec=repobox:repobox "$1" npm --prefix "{app_dir}/current" install --omit=dev
fi"""


def _layer(manifest: Manifest) -> str:
    slug = manifest.app.slug
    app_dir = f"/opt/repobox/apps/{slug}"
    packages = tuple(sorted(set((*manifest.build.system_packages, "ca-certificates", "curl", "avahi-daemon"))))
    runtime_hook = textwrap.indent(_runtime_hook(manifest), "        ")
    return f"""# METABEGIN
# X-Env-Layer-Name: repobox-app
# X-Env-Layer-Version: 1.0.0
# X-Env-Layer-Category: application
# X-Env-Layer-Desc: Install and enable an application generated by Repo2Box
# X-Env-Layer-Requires: systemd-net-min,systemd-timesyncd
# METAEND

---
mmdebstrap:
  packages:
{_yaml_packages(packages)}
  customize-hooks:
    - |
        set -eu
        if ! grep -q '^repobox:' "$1/etc/group"; then
          chroot "$1" groupadd --system repobox
        fi
        if ! grep -q '^repobox:' "$1/etc/passwd"; then
          chroot "$1" useradd --system --gid repobox --home-dir /var/lib/repobox --shell /usr/sbin/nologin repobox
        fi
        install -d -m 0755 "$1/var/lib/repobox/{slug}" "$1/etc/repobox"
        uid="$(awk -F: '$1 == "repobox" {{ print $3 }}' "$1/etc/passwd")"
        gid="$(awk -F: '$1 == "repobox" {{ print $3 }}' "$1/etc/group")"
        chown -R "$uid:$gid" "$1{app_dir}" "$1/var/lib/repobox/{slug}"
        chmod 0600 "$1/etc/repobox/{slug}.env"
{runtime_hook}
        chown -R root:root "$1{app_dir}"
    - $BDEBSTRAP_HOOKS/enable-units "$1" avahi-daemon
    - $BDEBSTRAP_HOOKS/enable-units "$1" repobox-{slug}
"""


def _config(image_name: str, target: str, hostname: str, ssh_enabled: bool) -> str:
    admin = "  user1sudo: nopasswd\n" if ssh_enabled else ""
    ssh = "\nssh:\n  pubkey_user1: ${@SRCROOT}/ssh-authorized-key.pub\n  pubkey_only: y\n" if ssh_enabled else ""
    return f"""device:
  layer: {target}
  hostname: {hostname}
{admin}
image:
  layer: image-rpios
  boot_part_size: 200%
  root_part_size: 3000M
  name: {image_name}

layer:
  base: trixie-minbase
  app: repobox-app
{ssh}"""


def prepare_image_source(
    source: Path,
    manifest: Manifest,
    target: str,
    output_dir: Path,
    *,
    hostname: str = "repobox",
    ssh_public_key: Path | None = None,
    force: bool = False,
) -> ImagePlan:
    manifest.validate()
    if target not in manifest.device.targets:
        raise ImageBuildError(f"Target {target!r} is not enabled by the manifest.")
    hostname = hostname.lower()
    if not HOSTNAME_PATTERN.fullmatch(hostname):
        raise ImageBuildError("Hostname must contain only lowercase letters, numbers, or internal hyphens.")

    output_dir = output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    image_name = f"{manifest.app.slug}-{target}"
    workspace = (output_dir / f"{image_name}-image-source").resolve()
    if output_dir not in workspace.parents:
        raise ImageBuildError("Unsafe image workspace path.")
    if workspace.exists():
        if not force:
            raise ImageBuildError(f"Image workspace already exists: {workspace}. Use --force to replace it.")
        shutil.rmtree(workspace)

    public_key = ""
    if ssh_public_key is not None:
        key_path = ssh_public_key.expanduser().resolve()
        try:
            public_key = key_path.read_text(encoding="utf-8").strip()
        except OSError as exc:
            raise ImageBuildError(f"Cannot read SSH public key {key_path}: {exc}") from exc
        if len(public_key) > 16_384 or not SSH_KEY_PATTERN.fullmatch(public_key):
            raise ImageBuildError("SSH public key is not a supported one-line OpenSSH public key.")

    layer_path = workspace / "layer" / "repobox-app.yaml"
    overlay = workspace / "layer" / "repobox-app.rootfs-overlay"
    app_root = overlay / "opt" / "repobox" / "apps" / manifest.app.slug / "current"
    app_root.mkdir(parents=True)
    _copy_source(source.resolve(), app_root, manifest.build.ignore)
    if not (app_root / "repobox.toml").exists():
        _write_text(app_root / "repobox.toml", manifest.to_toml())

    _write_text(layer_path, _layer(manifest))
    _write_text(
        overlay / "etc" / "systemd" / "system" / f"repobox-{manifest.app.slug}.service",
        _service(manifest),
    )
    _write_text(overlay / "etc" / "repobox" / f"{manifest.app.slug}.env", _environment_file(manifest))
    metadata = {
        "repobox_version": __version__,
        "rpi_image_gen_version": RPI_IMAGE_GEN_VERSION,
        "rpi_image_gen_commit": RPI_IMAGE_GEN_COMMIT,
        "app": manifest.app.name,
        "target": target,
        "hostname": hostname,
        "ssh_enabled": bool(public_key),
    }
    _write_text(
        overlay / "usr" / "share" / "repobox" / f"{manifest.app.slug}.json",
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
    )
    if public_key:
        _write_text(workspace / "ssh-authorized-key.pub", public_key + "\n")
    config_path = workspace / "config" / "repobox.yaml"
    _write_text(config_path, _config(image_name, target, hostname, bool(public_key)))
    _write_text(
        workspace / "BUILD-IMAGE.txt",
        f"""Repo2Box bootable image source

Backend: Raspberry Pi rpi-image-gen {RPI_IMAGE_GEN_VERSION}
Target: {target}
Image name: {image_name}.img

From the rpi-image-gen repository:
  ./rpi-image-gen build -S {workspace} -c repobox.yaml -f

The expected output is:
  work/image-{image_name}/{image_name}.img
""",
    )
    return ImagePlan(workspace, config_path, layer_path, image_name, target)


def build_image(plan: ImagePlan, engine_dir: Path, output_dir: Path) -> ImageResult:
    if platform.system() != "Linux":
        raise ImageBuildError(
            "Bootable image compilation requires Linux. Use --prepare-only here and run the GitHub Actions image workflow."
        )
    engine_dir = engine_dir.expanduser().resolve()
    executable = engine_dir / "rpi-image-gen"
    if not executable.is_file():
        raise ImageBuildError(f"rpi-image-gen executable not found: {executable}")
    if (engine_dir / ".git").exists() and shutil.which("git"):
        version = subprocess.run(
            ["git", "-C", str(engine_dir), "rev-parse", "HEAD"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if version.returncode != 0 or version.stdout.strip() != RPI_IMAGE_GEN_COMMIT:
            raise ImageBuildError(
                f"rpi-image-gen must be {RPI_IMAGE_GEN_VERSION} at commit {RPI_IMAGE_GEN_COMMIT}."
            )

    try:
        lint = subprocess.run(
            [str(executable), "metadata", "--lint", str(plan.layer_path)],
            cwd=engine_dir,
            check=False,
        )
    except OSError as exc:
        raise ImageBuildError(f"Could not start rpi-image-gen: {exc}") from exc
    if lint.returncode != 0:
        raise ImageBuildError(f"rpi-image-gen rejected the generated layer (exit {lint.returncode}).")
    try:
        build = subprocess.run(
            [str(executable), "build", "-S", str(plan.workspace), "-c", plan.config_path.name, "-f"],
            cwd=engine_dir,
            check=False,
        )
    except OSError as exc:
        raise ImageBuildError(f"Could not run rpi-image-gen: {exc}") from exc
    if build.returncode != 0:
        raise ImageBuildError(f"rpi-image-gen build failed with exit code {build.returncode}.")

    generated = engine_dir / "work" / f"image-{plan.image_name}" / f"{plan.image_name}.img"
    if not generated.is_file():
        raise ImageBuildError(f"Build completed but the expected image was not found: {generated}")
    output_dir = output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    destination = (output_dir / generated.name).resolve()
    if output_dir not in destination.parents:
        raise ImageBuildError("Unsafe image output path.")
    if generated.resolve() != destination:
        if destination.exists():
            destination.unlink()
        shutil.move(str(generated), destination)
    hasher = hashlib.sha256()
    with destination.open("rb") as image_file:
        for chunk in iter(lambda: image_file.read(8 * 1024 * 1024), b""):
            hasher.update(chunk)
    digest = hasher.hexdigest()
    return ImageResult(destination, digest, plan)
